.TH "Chapter 19 econ questions" 1 "chapter" 19 "econ questions"
.SH "question 1"


Because coal miners are exposed to dangerous and unhealthy enviornments, and less people want to be a coal miner

.SH "question 2"

Education falls under the category of human capital, which is the accumulation of investments in people such as education and on the job training. "Education is a capital because it represents the expenditure of resources at one time to raise productivity in the future"

.SH "question 3"

Becauese of signaling: Signaling is where an employer will see that a potential employee is a higher-skilled worker because they have an education, and thus will raise their wages

.SH "question 4"

The two condidtions that lead to superstars are the following:

"Every customer in the market wants to enjoy the good supplied by the best producer.
The good is produced with a technology that makes it possible for the best producer to supply every customer at low cost"

I wouldn't expect to see a superstar in denstistry, but it could happen: http://www.dentistrytoday.com/todays-dental-news/3459-dental-reality-show-on-the-way
Denstistry might not be good because people do not like going to the dentist, and thus would violate condition one. 

People enjoy music, so criteria one is true
Cd and digital distribution exist, so two is also true.

.SH "question 5"

Minimum-wage laws - Laws that force employers to give wages above equilibrium

Efficiency wages  - Wages employers give to employees to keep them happy, and working hard

Unions            - Employees that threaten to leave or not work unless they are paid more

.SH "question 6"

human capital       - People could be getting paid less because they spent more time getting education.

work ppl want to do - People could just not want to work a higher-paying job because of reasons like stress or otherwise

.SH "question 7"

They tend to lessen discrimination unless outside factors play a part. This is because employers who only care about money and not racism will hire ethnic workers who are willing to work for less due to the fact that they are not able to get work anywhere else

.SH "question 8"

The government passes a law that says black people can only be paid 5 dollars or less
