.TH "physical science chapter 14" 1 "Physical science" "chapter" 14
.SH "A flat, smooth surface that reflects light and forms an image is a(n) ____"

plane mirror

.SH "A(n) _______ uses two convex lenses lenses to magnify small,close objects"

refracting telescope

.SH "Every light ray that ravels paralell to the optical axis before hitting a concave mirror is reflected such that it passes through the ______"

Focal point

.SH "A(n) ______ is thicker in the middle than at the edges"

convex lens

.SH "The inner lining of the eye that converts light images into electrical signals is called the _____."

retina

.SH "Which of the following best describes image formation by a plane mirror?"

D

.SH "Which mirror can form an enlarged image"

Convex

.SH "Which of the following is used in a head-light or a flashlight to create a beam of light?"

Concave mirror

.SH "What do lenses do?"

Refract light

.SH "Which way does a concave lens bend light?"

C. away from its optical axis

.SH "What type of lens is used to correct farsightedness?"

convex

.SH "Which of the following is NOT part of a reflecting telescope?"

Concave lens

.SH "Which of the following images do light rays never pass trhough?"

B. Virtual

.SH "The image formed by a camera lense must always be which of the following?"

A. REaL

.SH "What happens to a light ray traveling parallel to the optical axis of a convex lens that passes through the lens?"

b. it passes through the focal ppoeint

